# Generated by Django 3.0 on 2019-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runodb',
            name='caption',
            field=models.TextField(blank=True, max_length=480),
        ),
    ]
