# Generated by Django 3.0 on 2020-01-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runoApp', '0002_auto_20191217_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='runodb',
            name='rate',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='runodb',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
