# Generated by Django 3.0 on 2020-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runoApp', '0003_auto_20200101_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='runodb',
            name='picture',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
