# Generated by Django 3.0 on 2020-01-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runoApp', '0005_kirjoittaja_valokuva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valokuva',
            name='poempicture',
        ),
        migrations.DeleteModel(
            name='Kirjoittaja',
        ),
        migrations.DeleteModel(
            name='Valokuva',
        ),
    ]
