# Generated by Django 3.0 on 2020-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runoApp', '0007_kirjoittaja_valokuva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaveri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
